= "{ " & Text.Combine( Table.AddColumn( SomenteTipoData, "Datas", each [Name] & "[" & [Column] & "]" )[Datas], " , " ) & " }"