let
    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("1VRNb8IwDP0vPcOPYIyKSfsQ69A0IQ4BzIjWJlMaDvv3S/IcNzDQdt0lfs+1X5w47mpVffrxzXM1qm6VV2yaxX1AE2PD+kA91skG9vHYBXBn9FZbfKy1Ue0Ql9MCQOytjsINdcqoMhueLCAMADKCRUnCBKfChCHwxemOeu/ojJYYO5QUwTU5rXYWokuvW9k7ElxMrfutanHOmrYH1ZHxnH/iOuep2ChwFvGbi2sIzXna73vycjdCQ4ZgOZR4ghjj9WhVkRkvG+gRG/T8jZSLWtb4Q7ZofEQoovHK+RwxM7uT4FIg4lz3V1hfiT4KiUihwCgazs8Q4ZENEgGlkhgjZHEMiuROyIBYtWAInNtW7yBs3SDGJL3M2GdOn7a21+a9uIrSc0ZTiey4kH/FBVl0ipsDwlcEkvcDG04LnqRTl/vxrEkPOryibP//bE/jeW2JBUBY8IV5nqtNMdCJ/ZzoqSaXfx1CS5ynuPxyjeYiwt3/ZXRR/KW5XX8D", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Idioma = _t, Data = _t, DataSQL = _t, Ano = _t, Mes = _t, MesAb = _t, MesNum = _t, InicioMes = _t, FinalMes = _t, MesAno = _t, MesAnoNum = _t, Dia = _t, SemanaNum = _t, InicioSemana = _t, FinalSemana = _t, SemanaAno = _t, SemanaAnoNum = _t, DiaSemana = _t, DiaSemanaAb = _t, DiaSemanaNum = _t, TrimestreNum = _t, Trimestre = _t, TrimestreAno = _t, TrimestreAnoNum = _t, Feriado = _t, DiaUtilNum = _t, DiaUtil = _t, AnoFiscal = _t, MesFechamentoNum = _t, MesFechamento = _t, MesFechamentoAb = _t, AnoFechamento = _t, MesAnoFechamento = _t, MesAnoFechamentoNum = _t, DataOffset = _t, SemanaOffset = _t, MesOffset = _t, TrimestreOffset = _t, AnoOffset = _t])
in
    Fonte